{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.4.2.jar",
          "url": "room-compiler-2.4.2.jar",
          "size": 3743933,
          "sha512": "92d1c227ad75d1acd4ac0e07834b9e7918006d76129579d217f6f6bff1d3e0093ba9b6be9540ea543a245431a250b0f49be3f2b57bb53d8010f2eb8d22108ecd",
          "sha256": "0e6930971a8b15f503e308da2c2f75587540cf5f014b664a555ac299197e4fca",
          "sha1": "de03a66ae88c970beeb78ae0e7c48af6419d3250",
          "md5": "4e75b6fc18ef6a1c64aa58ea132edbcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.36.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.4.2.jar",
          "url": "room-compiler-2.4.2.jar",
          "size": 3743933,
          "sha512": "92d1c227ad75d1acd4ac0e07834b9e7918006d76129579d217f6f6bff1d3e0093ba9b6be9540ea543a245431a250b0f49be3f2b57bb53d8010f2eb8d22108ecd",
          "sha256": "0e6930971a8b15f503e308da2c2f75587540cf5f014b664a555ac299197e4fca",
          "sha1": "de03a66ae88c970beeb78ae0e7c48af6419d3250",
          "md5": "4e75b6fc18ef6a1c64aa58ea132edbcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.2-sources.jar",
          "url": "room-compiler-2.4.2-sources.jar",
          "size": 446608,
          "sha512": "98a934ad05a7780d3d0e9b187758683dc6d001371f23ac474f21568dcf6a5d9429d9830db8cb127a47730c6d871e609cbe1708f30b1093b109c1110387c587dd",
          "sha256": "e66dae0952d3835190c798c2f05b70a3ed8dd285bd7b0ce852af97c2683004d8",
          "sha1": "995c9d97208758273013b314f486d6b9f367dc05",
          "md5": "d2c10d508788cff871dc37fcd6f34f82"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.2.jar",
          "url": "room-compiler-2.4.2.jar",
          "size": 3743933,
          "sha512": "92d1c227ad75d1acd4ac0e07834b9e7918006d76129579d217f6f6bff1d3e0093ba9b6be9540ea543a245431a250b0f49be3f2b57bb53d8010f2eb8d22108ecd",
          "sha256": "0e6930971a8b15f503e308da2c2f75587540cf5f014b664a555ac299197e4fca",
          "sha1": "de03a66ae88c970beeb78ae0e7c48af6419d3250",
          "md5": "4e75b6fc18ef6a1c64aa58ea132edbcf"
        }
      ]
    }
  ]
}
