{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.2.aar",
          "url": "room-ktx-2.4.2.aar",
          "size": 35508,
          "sha512": "4cd94858caa3784a8dcd31eafaf2d9bfcfa7651d8fd9d91129d77243e9914ab1499b5184c6dc580d7e2cfd6067f0ca034376d76c9baa4d72d6e2688849bdb064",
          "sha256": "23aac021051bce72413e037be3dc636380693a07f7dad914c1dafff54899293a",
          "sha1": "0ed0de9c9f296bf5ea4f05dcf6257980ee000f63",
          "md5": "3bd5cfa019f80646e9fda113da2c5f9b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.2.aar",
          "url": "room-ktx-2.4.2.aar",
          "size": 35508,
          "sha512": "4cd94858caa3784a8dcd31eafaf2d9bfcfa7651d8fd9d91129d77243e9914ab1499b5184c6dc580d7e2cfd6067f0ca034376d76c9baa4d72d6e2688849bdb064",
          "sha256": "23aac021051bce72413e037be3dc636380693a07f7dad914c1dafff54899293a",
          "sha1": "0ed0de9c9f296bf5ea4f05dcf6257980ee000f63",
          "md5": "3bd5cfa019f80646e9fda113da2c5f9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-ktx-2.4.2-sources.jar",
          "url": "room-ktx-2.4.2-sources.jar",
          "size": 6172,
          "sha512": "de695411f2de0eaddbceef38442573f628afbdeabe4a2ffc5564014f4106e4a0e8eeabc78acbe441598786b2e3929f9bd8d42d82ad44c02b13f244753814f566",
          "sha256": "216fd66c14a6c91f9488270add0604bebaa705e51309459a59cb33dc98343e46",
          "sha1": "8d0b5588d76f4f7843b5bc174d3a168604c285ad",
          "md5": "0e7ac736a01dac2aff569eeb682709fb"
        }
      ]
    }
  ]
}
