{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.2.aar",
          "url": "room-runtime-2.4.2.aar",
          "size": 137132,
          "sha512": "6fe70829985545473c4abd1ee11b3330dd943f1dca2370abe32c91a3546cf1411bfd70f30c618ced29dd58fb80e961586fddfdef1b7bafee14683f7610b7dc3c",
          "sha256": "b49477511a14b0d3f713d8b90ffce686ac161314111a5897a13aa82d4c892217",
          "sha1": "bc1a911cfb2161017bb32817befb5d6a304ca7a0",
          "md5": "a8d88d9cdaadf50a7424de64a3e1e6a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.2.aar",
          "url": "room-runtime-2.4.2.aar",
          "size": 137132,
          "sha512": "6fe70829985545473c4abd1ee11b3330dd943f1dca2370abe32c91a3546cf1411bfd70f30c618ced29dd58fb80e961586fddfdef1b7bafee14683f7610b7dc3c",
          "sha256": "b49477511a14b0d3f713d8b90ffce686ac161314111a5897a13aa82d4c892217",
          "sha1": "bc1a911cfb2161017bb32817befb5d6a304ca7a0",
          "md5": "a8d88d9cdaadf50a7424de64a3e1e6a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.4.2-sources.jar",
          "url": "room-runtime-2.4.2-sources.jar",
          "size": 96157,
          "sha512": "1a260d324c79bf24d897bb44b19c496fd77df5def29b52cbd9f2671ee0539bf690d14675f3873057d091763d3a6d33111c175f802fb39041ea02fb6d7667237a",
          "sha256": "2409606fa2e06a6218f8a3e99e11ccbc8b0ce3b60c3a0f813ba147c3578faa11",
          "sha1": "2c9eecfcf43be2af702d4ec1de12eddf475ec7fe",
          "md5": "d477d5cc4f5feec0c655503294990872"
        }
      ]
    }
  ]
}
