{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-safe-args-gradle-plugin",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-safe-args-gradle-plugin-2.3.5.jar",
          "url": "navigation-safe-args-gradle-plugin-2.3.5.jar",
          "size": 29582,
          "sha512": "ef50c96d1e9385281ef86fc4cdff87363cdc333f740c6a5bdf24a6fce21dbed89c829c84826656f8cf9e0c39d45bcae6cc9e8f38df0fdabff6a48b530c4d2fcb",
          "sha256": "249f5f2e829fa27a3af50c957d8a9e635d8b65fc220d1be9e80ad769d56e19b2",
          "sha1": "cf14547277bf60ff5268d1f04861a7f1944c5d84",
          "md5": "de3bee2b1514ee1a73c25893aa086339"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-safe-args-gradle-plugin-2.3.5.jar",
          "url": "navigation-safe-args-gradle-plugin-2.3.5.jar",
          "size": 29582,
          "sha512": "ef50c96d1e9385281ef86fc4cdff87363cdc333f740c6a5bdf24a6fce21dbed89c829c84826656f8cf9e0c39d45bcae6cc9e8f38df0fdabff6a48b530c4d2fcb",
          "sha256": "249f5f2e829fa27a3af50c957d8a9e635d8b65fc220d1be9e80ad769d56e19b2",
          "sha1": "cf14547277bf60ff5268d1f04861a7f1944c5d84",
          "md5": "de3bee2b1514ee1a73c25893aa086339"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-safe-args-gradle-plugin-2.3.5-sources.jar",
          "url": "navigation-safe-args-gradle-plugin-2.3.5-sources.jar",
          "size": 5213,
          "sha512": "0e96d5d14627a35b1c2040ac7021a578d266eba2f7fad659f13451e8563e8110a3b8019f2a44bf56eb258655738b9bd92fbf59288068830e2364d501bbf25d26",
          "sha256": "1193953242e2b5e7d2b3dee19d4775fecaa8fd6471d0136d27ff07e95596413f",
          "sha1": "c4085367cfc59747ee5ed5db7b526116e8775f1e",
          "md5": "787d7e4233a7b6cdc7435cc3c20a7efb"
        }
      ]
    }
  ]
}
