{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-safe-args-generator",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-safe-args-generator-2.3.5.jar",
          "url": "navigation-safe-args-generator-2.3.5.jar",
          "size": 154480,
          "sha512": "90d3dbe4dc25037c43169686155fa618353ade54ebf46d0b8cf0da569a47aeef926a05931fb9298671a6c7cdaf2679cdac987652b64bddfa043bcc4c15d01a4e",
          "sha256": "a78c4bea31b89a5b92cd2578589f0ece2c36c83babdc6478f7d621643265bdd0",
          "sha1": "831d436a8dfea4e2cb177dadacdd010bee69891b",
          "md5": "b40bc84cc97ac2c5ef813b46892225f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "xpp3",
          "module": "xpp3",
          "version": {
            "requires": "1.1.4c"
          }
        },
        {
          "group": "xmlpull",
          "module": "xmlpull",
          "version": {
            "requires": "1.1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-safe-args-generator-2.3.5.jar",
          "url": "navigation-safe-args-generator-2.3.5.jar",
          "size": 154480,
          "sha512": "90d3dbe4dc25037c43169686155fa618353ade54ebf46d0b8cf0da569a47aeef926a05931fb9298671a6c7cdaf2679cdac987652b64bddfa043bcc4c15d01a4e",
          "sha256": "a78c4bea31b89a5b92cd2578589f0ece2c36c83babdc6478f7d621643265bdd0",
          "sha1": "831d436a8dfea4e2cb177dadacdd010bee69891b",
          "md5": "b40bc84cc97ac2c5ef813b46892225f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-safe-args-generator-2.3.5-sources.jar",
          "url": "navigation-safe-args-generator-2.3.5-sources.jar",
          "size": 35299,
          "sha512": "2800b0ee0805e660d0f24064bf91260978baa0e25f54d31962f74d088b7184eafeeced3b3274945ccd58ebef8cc2f5f03b2002f1e2e4d5a9fa06d90465667569",
          "sha256": "813c83c0736ea11c3163ac393cab3c70295b281d82fc66184847942d0d22f07b",
          "sha1": "3feedc17c0df20df1b5d4d41df8d9c030e1a995d",
          "md5": "dfca8d584988983b805c6821b076bca8"
        }
      ]
    }
  ]
}
